baseURL: "https://serenevoid.github.io/"
title: Voice of the Void
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: true
buildExpired: false

minify:
  disableXML: false
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary


params:
  env: production
  title: Voice of the Void
  description: A personal Blog site and nothing more
  keywords: [Blog, Portfolio]
  author: Void
  images:
  - cover.png
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  ShowFullTextinRSS: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false
    title: Voice of the Void
    subtitle: "A personal blog site and nothing more"
    imageUrl: "profile.webp"
    imageWidth: 180
    imageHeight: 180
    imageTitle: profile
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Voice of the Void"
    Content: A simple blog and nothing more.

  socialIcons:
    - name: github
      url: "https://github.com/serenevoid"
    - name: Rss
      url: "index.xml"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 0.4
      minMatchCharLength: 0
      keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: search
      name:  Search
      url: /search
      weight: 1
    - identifier: archives
      name: Archives
      url: /archives
      weight: 2
    - identifier: tags
      name: Tags
      url: /tags
      weight: 3
    - identifier: about
      name: About
      url: /about
      weight: 4
    - identifier: contact
      name: Contact Me
      url: /contact
      weight: 5

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

